services:
  backend:
    build: ./backend
    container_name: app_backend_prod
    restart: unless-stopped
    env_file:
      - ./backend/.env.prod
    expose:
      - "5000"
    volumes:
      - ./backend:/app
      - ${FILE_STORAGE_ROOT_PROD}:${FILE_STORAGE_ROOT_PROD}
      - /var/run/docker.sock:/var/run/docker.sock
    command: ["gunicorn", "-b", "0.0.0.0:5000", "wsgi:app"]
    networks:
      - private_net

  frontend:
    build: ./frontend
    container_name: app_frontend_prod
    restart: unless-stopped
    env_file:
      - ./frontend/.env.prod
    expose:
      - "5173"
    command: ["sh", "-c", "npm run build && npm run preview -- --host 0.0.0.0 --port 5173"]
    networks:
      - private_net

  shinyserver:
    build: ./shiny
    container_name: app_shiny_prod
    restart: unless-stopped
    env_file:
      - ./shiny/.env.prod
    expose:
      - "3838"
    volumes:
      - ${SHINY_SERVER_APP_DIR_PROD}:/srv/shiny-server
      - renv_cache_dev:/renv/cache
      - r_libs_dev:/usr/local/lib/R/site-library
    networks:
      - private_net

  nginx_app:
    build: ./nginx
    container_name: app_nginx_app_prod
    restart: unless-stopped
    depends_on:
      - backend
      - frontend
      - shinyserver
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/ssl:/etc/nginx/ssl
    networks:
      - private_net
      - public_net

volumes:
  renv_cache_prod:
    driver: local

networks:
  private_net:
    driver: bridge
  public_net:
    driver: bridge