services:
  backend:
    build: ./backend
    container_name: app_backend_prod
    restart: unless-stopped
    env_file:
      - ./backend/.env.prod
    expose:
      - "5000"
    volumes:
      - ./shared_files:/srv/resources
    command: ["gunicorn", "-b", "0.0.0.0:5000", "wsgi:app"]
    networks:
      - private_net

  frontend:
    build: ./frontend
    container_name: app_frontend_prod
    restart: unless-stopped
    env_file:
      - ./frontend/.env.prod
    expose:
      - "5173"
    command: ["sh", "-c", "npm run build && npm run preview -- --host 0.0.0.0 --port 5173"]
    networks:
      - private_net

  shinyserver:
    build: ./shiny
    container_name: app_shiny_prod
    restart: unless-stopped
    env_file:
      - ./shiny/.env.prod
    environment:
      FILE_STORAGE_ROOT: /srv/resources
      SHINY_SERVER_APP_DIR: /srv/resources/shinny-apps
    expose:
      - "3838"
    volumes:
      - ./shared_files:/srv/resources
      - renv_cache_prod:/renv/cache
    networks:
      - private_net

  nginx_app:
    build: ./nginx
    container_name: app_nginx_app_prod
    restart: unless-stopped
    depends_on:
      - backend
      - frontend
      - shinyserver
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/ssl:/etc/nginx/ssl
    networks:
      - private_net
      - public_net

volumes:
  renv_cache_prod:
    driver: local

networks:
  private_net:
    driver: bridge
  public_net:
    driver: bridge